usrName: "angell"
logLevel: "debug"
repoURLGeneric: "git@gitea.kdl/"
pathGeneric: "/home/kdl/reposs/"
pemFile: "/home/kdl/.ssh/id_rsa"
pemFilePassword: ""
checkFrequencySeconds: 5
mongodb:
  uri: "mongodb://admin:123456@localhost:27017/admin"
  dbName: "kdl"
  projectCollName: "projects"
  userCollName: "users"
