kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oauth
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get","update","list", "create"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: usertools
rules:
  - apiGroups: ["sci-toolkit.konstellation.io"]
    resources: ["usertools"]
    verbs: ["*"]
---
{{ if not .Values.kdl.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dashboard
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
{{ end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub-oauth
subjects:
  - kind: ServiceAccount
    name: hub
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: oauth
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-oauth
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: oauth
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-usertools
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: usertools
  apiGroup: rbac.authorization.k8s.io
---
{{ if not .Values.kdl.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-dashboard
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: dashboard
  apiGroup: rbac.authorization.k8s.io
{{ end }}
